name: Quality check (lint files and run e2e tests)

on: [pull_request]

jobs:
  lint_files:
    runs-on: 'ubuntu-latest'
    env:
      DATABASE_CONNECTION_URL: ${{ secrets.DATABASE_CONNECTION_URL }}
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./
          # next build also checks for TypeScript errors and lints files
          build: npm run build
          start: npm start
