name: Sync certificates (weekly at sunday 23:59)

on:
  schedule:
    # Every Sunday at 23:59
    - cron: '59 23 * * 7'

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Sync SFT certificates
        run: |
          curl --request GET \
          --url 'https://sertifikaattilukija.netlify.app/api/sync/sft' \
          --header 'Authorization: ${{ secrets.AUTH_TOKEN }}'
      - name: Sync wwf green office certificates
        run: |
          curl --request GET \
          --url 'https://sertifikaattilukija.netlify.app/api/sync/wwf-green-office' \
          --header 'Authorization: ${{ secrets.AUTH_TOKEN }}'
