name: Sync certificates (weekly at sunday 23:59)

on:
  schedule:
    # Every Sunday at 23:59
    - cron: '59 23 * * 7'

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Sync SFT certificates
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://sertifikaattilukija.netlify.app/api/sync/sft'
          method: 'GET'
          customerHeaders: '{ "Authorization": ${{ secrets.AUTH_TOKEN }} }'
      - name: Sync SFT certificates
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://sertifikaattilukija.netlify.app/api/sync/wwf-green-office'
          method: 'GET'
          customerHeaders: '{ "Authorization": ${{ secrets.AUTH_TOKEN }} }'
